#!/usr/bin/expect -f

# Specify the absolute path to the dotfile
set pw_file "$env(HOME)/bin/.mypw"

# Check if the dotfile exists
if { [file exists $pw_file] } {
    # Dotfile exists, read its contents
    set mypw [exec cat $pw_file]

    # Run the pacman command using expect
    spawn sudo pacman -Syu
    set timeout 30
    expect "*assword*"
    send "$mypw\r"
    expect {
        "*nstallation*" { send "Y\r" }
        "*there is nothing to do*" { exit 0 }
    }
    expect eof
} else {
    # Dotfile does not exist, uses regular update
    spawn sudo pacman -Syu
    interact
}

